version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /src
    schedule:
      interval: weekly
    target-branch: dev
    groups:
      web-dependencies:
        patterns:
          - "*"
