# -*- coding: utf-8 -*-
"""Test AmplifyP implementation using real life examples."""

import logging

from amplifyp.dna import DNA, DNAType, DNADirection, Primer
from amplifyp.replication import Repliconf
from amplifyp.settings import Settings

amplify4_template = DNA(
    """CATGATGAAATAACATAAGGTGGTCCCGTCGAAAgccgaagcGCAGAGCTGTCATACTCGAAGGCAGCAGCGA
    CCTTCATCTCGTCGAAAGCGAGTACGCAAAGCTTGTCGGCGTCATCAACTCCATCACTGTCCATTAGGTCTATGAC
    CACATCCAAACATCCTCTTTTTATGTCCACATCTGATAACCATCTGTACAAAGTCGTACGACTGGGCAAAGGAAAT
    CCTTTTTTGTACAGATGGTTATACGCTCGAGGGCCTGCGGTGTGGAGACAAATAGCTGTAGAAATGTCGTCGGAAT
    TGAACGTAGCTCTTTGTCCACCATTCTTCAGTATCCGTATCTGCGTGTCCGTGAAGATTTTGCGTAGAGACTCCTC
    CAActgttgagactccctCAGCTGCTGCTCTAAACGACGCATTTCGTACTCCAAAGTACGAATTTTTTCCCTCAAG
    CTCTTATTTTCATTAAACAATGAACAGGACCTAACGCACAGTCACGTTATTGTTTACATAAATGATTTTTTTTACT
    ATTCAAACTTACTCTGTTTGTGTACTCCCACTGGTATAGCCTTCTTTTATCTTTTCTGGTTCAGGCTCTATCACTT
    TACTAGGTACGGCATCTGCGTTGAGTCGCCTCCTTTTAAATGTCTGACCTTTTGCAGGTGCAGCCTTCCACTGCGA
    ATCATTAAAGTGGGTATCACAAATTTGGGAGTTTTCACCAAGGCTGCACCCAAGGCTCTGCTCCCACAATTTTCTC
    TTAATAGCACACTTCGGCACGTGAATTAATTTTACTTTtTTnTTccagtcacagctttgcagcTaAAATTTGCAAT
    ATTTCATTTTTTTTTATTCCACGTAAGGGTTAATGTTTTCAAAAAAAAATTCGTCCGCACACAACCTTTCCTCTCA
    ACAAGCAAACGTGCACTGAATTTAAGTGTatacttcggtaaTGATATTGTTTACGAGCCAAGCGACTATGTCCAAC
    TGGCTATTGTTCGTGGTCTAAAAAAATCGTGGAAGCAGCCAGTTTTTTTCGATTTTAATACCCGAATGGACCCGGA
    TACTCTTAACAATATATTAAGGAAACTGCATAGGAAAGGATATTTAGTAGTTGCTATTGTATCCGATTTAGGTACC
    GGAAACCAAAAGCTATGGACAGAGCTCGGTATATCAGAATGTAAGTTTCGTATATTACAAAAATCAGATAATCCTT
    GAAATTCCATTTTTTAGCAAAAACCTGGTTTAGCCATCCTGCAGATGACCATTTAAAGATTTTCGTTTTTTCGGAT
    ACGCCACATTTAATTAAGTTAGTCCGTAACCACTATGTGGATTCCGGATTAACAATAAATGGGAAAAAATTAACAA
    AAAAAACAATTCAGGAGGCACTTCATCTTTGCAACAAGTCCGATCTGTCTATCCTCTTTAAAATTAATGAAAATCA
    CATTAATGTTCGATCGCTCGCAAAACAGAAGGTTAAATTGGCTACCCAGCTGTTTTCGAATACCACCGCTAGCTCG
    ATCAGACGCTGCTATTCATTGGGGTATGACATTGAAAATGCCACCGAAACTGCGGACTTCTTCAAATTGATGAATG
    ATTGGTTCGACATTTTTAATTCTAAATTGTCCACATCCAATTGCATTGAGTGCTCGCAACCTTATGGCAAGCAGTT
    GGATATACAGAATGATATTTTGAATCGAATGTCGGAAATTATGCGAACAGGAATTCTGGATAAACCCAAAAGGCTC
    CCATTTCAAAAAGGTATCATTGTGAATAATGCTTCGCTTGATGGCTTGTATAAATATTTGCAAGAAAACTTCAGTA
    TGCAATACATATTAACAAGCCGTCTCAACCAAGACATTGTGGAGCATTTTTTTGGCAGCATGCGATCGAGAGGTGG
    ACAATTCGACCATCCCACTCCACTGCAGTTTAAGTATAGGTTAAGAAAATATATAATAGGTATGACAAATTTAAAA
    GAATGCGTAAACAAAAATGTAATTCCATGATTTATAATTGTTTAATGTTTAGCTATATGTTTCAGGAAAGTTTCAG
    TTGAGAATGTAGGTAGTTATGTGCTGTCTATTGTGTTTTGTCTTTTATCTGTTTCTTTTCATTTTATTATTTAATC
    ATTATCCTTTTGCTTATCCAGCCAGGAATACAGAAATGTTAAGAAATTCGGGAAATATCGAAGAGGACAACTCTGA
    AAGCTGGCTTAATTTAGATTTCAGTTCTAAAGAAAACGAAAATAAAAGTAAAGATGATGAGCCTGTCGATGATGAG
    CCTGTCGATGAGATGTTAAGCAATATAGATTTCACCGAAATGGATGAgttgacggaggatgcgatggAATATATCG
    CGGGCTATGTCATTAAAAAATTGAGAATCAGTGACAAAGTAAAAGAAAAAAGAGACATCCACTTAAcgtatgcttg
    caataagtgcGAGTGAAAGGAATAGTATTCTGAGTGTCGTATTGAGTCTGAGTGAGACAGCGATATGATTGTTGAT
    TAACccttagcatgtccgtggggtTTGAATTAACTCATAATATTAATTAGACGAAATTATTTTTAAAGTTTTATTT
    TTAATAATTTGGAGTTTCCAATTAACTTTTGTTTTTGATTTTTAATTTCAATTTTTTTGTTGAAGTACTTAATTCT
    AAAATATATTCTAATTTTAAAATAAAAAGATTTTACTTGTTTATCAACATCGACGTTTCGCGCTGCTAATATTAAT
    TTTTCCTTTACATTATTTGTAATTTCAAAATTATTATTATTTGTATAATGCAAAAAAATACATTCTAGCTCTTTTA
    ACTTCTCTTGAAATTTTTCGGACGGCTTAATAAGTCCGCCGTGAGACACCTCGTCGACGTATGTAAATGTCAAAGC
    CGACGGGACCACCTTATGTTATTTCATCATG""",
    DNAType.LINEAR,
    "Template",
)

primer_1423 = Primer("GCCAAAGTGTGTTGGC", "1423")
primer_20049 = Primer("CAGATGTGGACATAAAAAGACAAT", "20049")


def test_search_primer_20049() -> None:
    """Test: search for primer 20049 in the Amplify 4 example template."""
    repliconf = Repliconf(amplify4_template, primer_20049, Settings)
    repliconf.search()
    origin_id = repliconf.origin_id
    print(origin_id)

    origin_1 = repliconf.origin(DNADirection.FWD, origin_id[DNADirection.FWD][0])
    logging.info(origin_1)
    logging.info(origin_1.primability)
    logging.info(origin_1.stability)
    logging.info(origin_1.quality)
    assert origin_1.primability == 0.8188405797101449
    assert origin_1.stability == 0.4838709677419355
    assert origin_1.quality == 0.12838943431510044

    origin_2 = repliconf.origin(DNADirection.REV, origin_id[DNADirection.REV][0])
    logging.info(origin_2)
    logging.info(origin_2.primability)
    logging.info(origin_2.stability)
    logging.info(origin_2.quality)
    assert origin_2.primability == 0.855072463768116
    assert origin_2.stability == 0.9005376344086021
    assert origin_2.quality == 0.6945126227208976
