"""Built-in test examples from Amplify 4."""

from amplifyp.dna import DNA, DNAType, Primer

amplify4_linear_example = DNA(
    """CATGATGAAATAACATAAGGTGGTCCCGTCGAAAgccgaagcGCAGAGCTGTCATACTCGAAGGCAGCAGCGA
    CCTTCATCTCGTCGAAAGCGAGTACGCAAAGCTTGTCGGCGTCATCAACTCCATCACTGTCCATTAGGTCTATGAC
    CACATCCAAACATCCTCTTTTTATGTCCACATCTGATAACCATCTGTACAAAGTCGTACGACTGGGCAAAGGAAAT
    CCTTTTTTGTACAGATGGTTATACGCTCGAGGGCCTGCGGTGTGGAGACAAATAGCTGTAGAAATGTCGTCGGAAT
    TGAACGTAGCTCTTTGTCCACCATTCTTCAGTATCCGTATCTGCGTGTCCGTGAAGATTTTGCGTAGAGACTCCTC
    CAActgttgagactccctCAGCTGCTGCTCTAAACGACGCATTTCGTACTCCAAAGTACGAATTTTTTCCCTCAAG
    CTCTTATTTTCATTAAACAATGAACAGGACCTAACGCACAGTCACGTTATTGTTTACATAAATGATTTTTTTTACT
    ATTCAAACTTACTCTGTTTGTGTACTCCCACTGGTATAGCCTTCTTTTATCTTTTCTGGTTCAGGCTCTATCACTT
    TACTAGGTACGGCATCTGCGTTGAGTCGCCTCCTTTTAAATGTCTGACCTTTTGCAGGTGCAGCCTTCCACTGCGA
    ATCATTAAAGTGGGTATCACAAATTTGGGAGTTTTCACCAAGGCTGCACCCAAGGCTCTGCTCCCACAATTTTCTC
    TTAATAGCACACTTCGGCACGTGAATTAATTTTACTTTtTTnTTccagtcacagctttgcagcTaAAATTTGCAAT
    ATTTCATTTTTTTTTATTCCACGTAAGGGTTAATGTTTTCAAAAAAAAATTCGTCCGCACACAACCTTTCCTCTCA
    ACAAGCAAACGTGCACTGAATTTAAGTGTatacttcggtaaTGATATTGTTTACGAGCCAAGCGACTATGTCCAAC
    TGGCTATTGTTCGTGGTCTAAAAAAATCGTGGAAGCAGCCAGTTTTTTTCGATTTTAATACCCGAATGGACCCGGA
    TACTCTTAACAATATATTAAGGAAACTGCATAGGAAAGGATATTTAGTAGTTGCTATTGTATCCGATTTAGGTACC
    GGAAACCAAAAGCTATGGACAGAGCTCGGTATATCAGAATGTAAGTTTCGTATATTACAAAAATCAGATAATCCTT
    GAAATTCCATTTTTTAGCAAAAACCTGGTTTAGCCATCCTGCAGATGACCATTTAAAGATTTTCGTTTTTTCGGAT
    ACGCCACATTTAATTAAGTTAGTCCGTAACCACTATGTGGATTCCGGATTAACAATAAATGGGAAAAAATTAACAA
    AAAAAACAATTCAGGAGGCACTTCATCTTTGCAACAAGTCCGATCTGTCTATCCTCTTTAAAATTAATGAAAATCA
    CATTAATGTTCGATCGCTCGCAAAACAGAAGGTTAAATTGGCTACCCAGCTGTTTTCGAATACCACCGCTAGCTCG
    ATCAGACGCTGCTATTCATTGGGGTATGACATTGAAAATGCCACCGAAACTGCGGACTTCTTCAAATTGATGAATG
    ATTGGTTCGACATTTTTAATTCTAAATTGTCCACATCCAATTGCATTGAGTGCTCGCAACCTTATGGCAAGCAGTT
    GGATATACAGAATGATATTTTGAATCGAATGTCGGAAATTATGCGAACAGGAATTCTGGATAAACCCAAAAGGCTC
    CCATTTCAAAAAGGTATCATTGTGAATAATGCTTCGCTTGATGGCTTGTATAAATATTTGCAAGAAAACTTCAGTA
    TGCAATACATATTAACAAGCCGTCTCAACCAAGACATTGTGGAGCATTTTTTTGGCAGCATGCGATCGAGAGGTGG
    ACAATTCGACCATCCCACTCCACTGCAGTTTAAGTATAGGTTAAGAAAATATATAATAGGTATGACAAATTTAAAA
    GAATGCGTAAACAAAAATGTAATTCCATGATTTATAATTGTTTAATGTTTAGCTATATGTTTCAGGAAAGTTTCAG
    TTGAGAATGTAGGTAGTTATGTGCTGTCTATTGTGTTTTGTCTTTTATCTGTTTCTTTTCATTTTATTATTTAATC
    ATTATCCTTTTGCTTATCCAGCCAGGAATACAGAAATGTTAAGAAATTCGGGAAATATCGAAGAGGACAACTCTGA
    AAGCTGGCTTAATTTAGATTTCAGTTCTAAAGAAAACGAAAATAAAAGTAAAGATGATGAGCCTGTCGATGATGAG
    CCTGTCGATGAGATGTTAAGCAATATAGATTTCACCGAAATGGATGAgttgacggaggatgcgatggAATATATCG
    CGGGCTATGTCATTAAAAAATTGAGAATCAGTGACAAAGTAAAAGAAAAAAGAGACATCCACTTAAcgtatgcttg
    caataagtgcGAGTGAAAGGAATAGTATTCTGAGTGTCGTATTGAGTCTGAGTGAGACAGCGATATGATTGTTGAT
    TAACccttagcatgtccgtggggtTTGAATTAACTCATAATATTAATTAGACGAAATTATTTTTAAAGTTTTATTT
    TTAATAATTTGGAGTTTCCAATTAACTTTTGTTTTTGATTTTTAATTTCAATTTTTTTGTTGAAGTACTTAATTCT
    AAAATATATTCTAATTTTAAAATAAAAAGATTTTACTTGTTTATCAACATCGACGTTTCGCGCTGCTAATATTAAT
    TTTTCCTTTACATTATTTGTAATTTCAAAATTATTATTATTTGTATAATGCAAAAAAATACATTCTAGCTCTTTTA
    ACTTCTCTTGAAATTTTTCGGACGGCTTAATAAGTCCGCCGTGAGACACCTCGTCGACGTATGTAAATGTCAAAGC
    CGACGGGACCACCTTATGTTATTTCATCATG""",
    DNAType.LINEAR,
    "Linear Template",
)

primer_1423 = Primer("GCCAAAGTGTGTTGGC", "1423")
primer_2223 = Primer("CGTCCGCACACAACCTTTCC", "2223")
primer_20049 = Primer("CAGATGTGGACATAAAAAGACAAT", "20049")

# 1701 and 11bp form an amplified fragment of 660bp
primer_11bp = Primer("ATTAACCCTTA", "11bp")
primer_1701 = Primer("CGACTGGGCAAAGGAAATCC", "1701")
fragment_660bp = DNA(
    """cgactgggcaaaggaaatccTTTTTTGTACAGATGGTTATACGCTCGAGGGCCTGCGGTGTGGAGACAAATAG
    CTGTAGAAATGTCGTCGGAATTGAACGTAGCTCTTTGTCCACCATTCTTCAGTATCCGTATCTGCGTGTCCGTGAA
    GATTTTGCGTAGAGACTCCTCCAACTGTTGAGACTCCCTCAGCTGCTGCTCTAAACGACGCATTTCGTACTCCAAA
    GTACGAATTTTTTCCCTCAAGCTCTTATTTTCATTAAACAATGAACAGGACCTAACGCACAGTCACGTTATTGTTT
    ACATAAATGATTTTTTTTACTATTCAAACTTACTCTGTTTGTGTACTCCCACTGGTATAGCCTTCTTTTATCTTTT
    CTGGTTCAGGCTCTATCACTTTACTAGGTACGGCATCTGCGTTGAGTCGCCTCCTTTTAAATGTCTGACCTTTTGC
    AGGTGCAGCCTTCCACTGCGAATCATTAAAGTGGGTATCACAAATTTGGGAGTTTTCACCAAGGCTGCACCCAAGG
    CTCTGCTCCCACAATTTTCTCTTAATAGCACACTTCGGCACGTGAATTAATTTTACTTTTTTNTTCCAGTCACAGC
    TTTGCAGCTAAAATTTGCAATATTTCATTTTTTTTTATTCCACGtaagggttaat""",
    DNAType.LINEAR,
    "660bp",
)

# 10290 and 11bp form an amplified fragment of 177bp
primer_10290 = Primer("GTGGGTATCACAAATTTGGG", "10290")
fragment_177bp = DNA(
    """gtgggtatcacaaatttgggAGTTTTCACCAAGGCTGCACCCAAGGCTCTGCTCCCACAATTTTCTCTTAATA
    GCACACTTCGGCACGTGAATTAATTTTACTTTTTTNTTCCAGTCACAGCTTTGCAGCTAAAATTTGCAATATTTCA
    TTTTTTTTTATTCCACGtaagggttaat""",
    DNAType.LINEAR,
    "177bp",
)

# 11bp and 10289 form an amplified fragment of 220bp
primer_10289 = Primer("GCAGCGCGAAACGTCGATGT", "10289")
fragment_220bp = DNA(
    """attaacccttaGCATGTCCGTGGGGTTTGAATTAACTCATAATATTAATTAGACGAAATTATTTTTAAAGTTT
    TATTTTTAATAATTTGGAGTTTCCAATTAACTTTTGTTTTTGATTTTTAATTTCAATTTTTTTGTTGAAGTACTTA
    ATTCTAAAATATATTCTAATTTTAAAATAAAAAGATTTTACTTGTTTATCAacatcgacgtttcgcgctgc""",
    DNAType.LINEAR,
    "220bp",
)
