# Copyright (C) 2026 Fufu Fang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Dimer primer analyser for AmplifyP."""

from typing import cast

from amplifyp.amplicon import Amplicon, AmpliconGenerator
from amplifyp.dna import Primer
from amplifyp.repliconf import Repliconf
from amplifyp.settings import ReplicationSettings


class DimerPrimerAnalyser:
    """Dimer primer analyser for AmplifyP."""

    def __init__(
        self, primers: list[Primer], settings: ReplicationSettings
    ) -> None:
        """Initialize the dimer primer analyser."""
        self.primers = primers
        self.settings = settings

    def add_primer(self, primer: Primer) -> None:
        """Add a primer to the analyser."""
        self.primers.append(primer)

    def remove_primer(self, primer: Primer) -> None:
        """Remove a primer from the analyser."""
        self.primers.remove(primer)

    def get_amplicons(self, template: Primer) -> list[Amplicon]:
        """Return the amplicons generated by a primer."""
        amplicon_generator = AmpliconGenerator(template)
        for primer in self.primers:
            repliconf = Repliconf(template, primer, self.settings)
            amplicon_generator.add(repliconf)
        return cast(list[Amplicon], amplicon_generator.get_amplicons())

    def get_all_amplicons(self) -> list[Amplicon]:
        """Return all amplicons generated by all primers."""
        all_amplicons: list[Amplicon] = []
        for primer in self.primers:
            all_amplicons.extend(self.get_amplicons(primer))
        return all_amplicons
