name: Pull Request on stable
on:
  pull_request:
    branches: [stable]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    name: Run tests and checks (${{ matrix.os }} - Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12', '3.13', '3.14']
    env:
      PYTHONUTF8: 1
      FLET_CLI_NO_RICH_OUTPUT: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install .[dev,e2e] pre-commit
      - name: Run pre-commit checks
        env:
          SKIP: pytest
        run: |
          pre-commit run --all-files --show-diff-on-failure
      - name: Run unit tests
        run: |
          pytest -v --cov=src/amplifyp --cov-report=xml
      - name: Run pyright analysis
        run: |
          pyright
      - name: Build Flet web app (Linux only, Python 3.13 only)
        if: runner.os == 'Linux' && matrix.python-version == '3.13'
        run: |
          bash ./build_static.sh --base-url /${{ github.event.repository.name }}/
      - name: Display coverage report (Linux only, Python 3.13 only)
        if: runner.os == 'Linux' && matrix.python-version == '3.13'
        run: |
          coverage report -m
      - name: Upload coverage to Codecov (Linux only, Python 3.13 only)
        if: runner.os == 'Linux' && matrix.python-version == '3.13'
        uses: codecov/codecov-action@v7
      - name: Run E2E tests (Linux only, Python 3.13 only)
        if: runner.os == 'Linux' && matrix.python-version == '3.13'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb tesseract-ocr libtesseract-dev
          playwright install --with-deps chromium
          xvfb-run -a pytest -v -s -m e2e
